# This file generates the GitHub Actions matrix
---
include:
  # Dongle: XIAO BLE with cyber60_dongle + prospector_adapter shields
  - board: xiao_ble//zmk
    shield: cyber60_dongle prospector_adapter
  # Keyboard: Cyber60 as left half
  - board: cyber60_rev_d
    shield: cyber60_left
